use DBRECATALOG;

SELECT * FROM TBCATALOG_ITEM;
SELECT * FROM TBCATALOG;
SELECT * FROM TBSOURCE_REPOSITORY;

delete from TBCATALOG_item
 where ID = "batata";

SELECT * FROM TBPROJECT;

SELECT * FROM TBRUNTIME_DEPENDENCY;
SELECT * FROM TBCOMPILE_DEPENDENCY;

 delete from TBCATALOG_ITEM where id like '%R1PAB001%';
 delete from TBRUNTIME_DEPENDENCY;
 delete from TBPROJECT;


-- delete  from TBPROJECT;
DELETE FROM TBCATALOG_ITEM where id = 'FINANCEIRO.R1PAB001';
SELECT * FROM TBPROPERTY_CATALOG_ITEM;



DROP TABLE IF EXISTS TBPROPERTY_CATALOG_ITEM;
DROP TABLE IF EXISTS TBCATALOG;
DROP TABLE IF EXISTS TBSOURCE_REPOSITORY;
DROP TABLE IF EXISTS TBSOURCE;
DROP TABLE IF EXISTS TBVERSION;
commit;

DROP TABLE IF EXISTS TBCATALOG_ITEM;

CREATE TABLE TBCATALOG_ITEM (
    ID VARCHAR(255) NOT NULL,
    CREATED_ON DATETIME(6) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    PARENT_ID VARCHAR(255)
);

CREATE INDEX IX_PK_TBCATALOG_ITEM ON TBCATALOG_ITEM (ID);    
    
ALTER TABLE TBCATALOG_ITEM
  ADD CONSTRAINT PK_TBCATALOG_ITEM
    PRIMARY KEY (ID);     
    
ALTER TABLE TBCATALOG_ITEM ADD CONSTRAINT FK1_TBCATALOG_ITEM  FOREIGN KEY (PARENT_ID)
	REFERENCES TBCATALOG_ITEM (ID);   
    
CREATE INDEX IX_CATALOG_ITEM ON TBCATALOG_ITEM (NAME ASC);

    select * from TBCATALOG_ITEM;
    
    delete from TBCATALOG_ITEM;
----------------------------------------------------------------------------------------
DROP TABLE IF EXISTS TBCATALOG;

CREATE TABLE TBCATALOG (
    ID VARCHAR(255) NOT NULL
);

CREATE INDEX IX_PK_TBCATALOG ON TBCATALOG (ID);    
    
ALTER TABLE TBCATALOG
  ADD CONSTRAINT PK_TBCATALOG
    PRIMARY KEY (ID);  
    
ALTER TABLE TBCATALOG ADD CONSTRAINT FK1_TBCATALOG  FOREIGN KEY (ID)
	REFERENCES TBCATALOG_ITEM (ID);  
    
----------------------------------------------------------------------------------------
DROP TABLE IF EXISTS TBSOURCE_REPOSITORY;

CREATE TABLE TBSOURCE_REPOSITORY (
    ID VARCHAR(255) NOT NULL
);

-- select * from TBSOURCE_REPOSITORY;

CREATE INDEX IX_PK_TBSOURCE_REPOSITORY ON TBSOURCE_REPOSITORY (ID);    
    
ALTER TABLE TBSOURCE_REPOSITORY
  ADD CONSTRAINT PK_TBSOURCE_REPOSITORY
    PRIMARY KEY (ID);  
    
ALTER TABLE TBSOURCE_REPOSITORY ADD CONSTRAINT FK1_TBSOURCE_REPOSITORY  FOREIGN KEY (ID)
	REFERENCES TBCATALOG_ITEM (ID);  
    
----------------------------------------------------------------------------------------
DROP TABLE IF EXISTS TBSOURCE;

CREATE TABLE TBSOURCE (
    ID VARCHAR(255) NOT NULL
);

-- select * from TBSOURCE_REPOSITORY;

CREATE INDEX IX_PK_TBSOURCE ON TBSOURCE (ID);    
    
ALTER TABLE TBSOURCE
  ADD CONSTRAINT PK_TBSOURCE
    PRIMARY KEY (ID);  
    
ALTER TABLE TBSOURCE ADD CONSTRAINT FK1_TBSOURCE  FOREIGN KEY (ID)
	REFERENCES TBCATALOG_ITEM (ID);      
    
----------------------------------------------------------------------------------------
DROP TABLE IF EXISTS TBVERSION;

CREATE TABLE TBVERSION (
    ID VARCHAR(255) NOT NULL
);

-- select * from TBSOURCE_REPOSITORY;

CREATE INDEX IX_PK_TBVERSION ON TBVERSION (ID);    
    
ALTER TABLE TBVERSION
  ADD CONSTRAINT PK_TBVERSION
    PRIMARY KEY (ID);  
    
ALTER TABLE TBVERSION ADD CONSTRAINT FK1_TBVERSION  FOREIGN KEY (ID)
	REFERENCES TBCATALOG_ITEM (ID);   
    
----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------
DROP TABLE IF EXISTS TBPROJECT;

CREATE TABLE TBPROJECT (
    ID VARCHAR(255) NOT NULL
);

-- select * from TBSOURCE_REPOSITORY;

CREATE INDEX IX_PK_TBPROJECT ON TBPROJECT (ID);    
    
ALTER TABLE TBPROJECT
  ADD CONSTRAINT PK_TBPROJECT
    PRIMARY KEY (ID);  
    
ALTER TABLE TBPROJECT ADD CONSTRAINT FK1_TBPROJECT  FOREIGN KEY (ID)
	REFERENCES TBCATALOG_ITEM (ID);   

---------------------------------------------------------------------------------------------------------------
DROP TABLE IF EXISTS TBRUNTIME_DEPENDENCY;

CREATE TABLE TBRUNTIME_DEPENDENCY (
    ID VARCHAR(255) NOT NULL
);

-- delete from TBCOMPILE_DEPENDENCY;

-- select * from TBSOURCE_REPOSITORY;

CREATE INDEX IX_PK_TBRUNTIME_DEPENDENCY ON TBRUNTIME_DEPENDENCY (ID);    
    
ALTER TABLE TBRUNTIME_DEPENDENCY
  ADD CONSTRAINT PK_TBRUNTIME_DEPENDENCY
    PRIMARY KEY (ID);  
    
ALTER TABLE TBRUNTIME_DEPENDENCY ADD CONSTRAINT FK1_TBRUNTIME_DEPENDENCY  FOREIGN KEY (ID)
	REFERENCES TBCATALOG_ITEM (ID); 
---------------------------------------------------------------------------------------------------------------
DROP TABLE IF EXISTS TBCOMPILE_DEPENDENCY;

-- delete from TBCOMPILE_DEPENDENCY;

CREATE TABLE TBCOMPILE_DEPENDENCY (
    ID VARCHAR(255) NOT NULL
);

CREATE INDEX IX_PK_TBCOMPILE_DEPENDENCY ON TBCOMPILE_DEPENDENCY (ID);    
    
ALTER TABLE TBCOMPILE_DEPENDENCY
  ADD CONSTRAINT PK_TBCOMPILE_DEPENDENCY
    PRIMARY KEY (ID);  
    
ALTER TABLE TBCOMPILE_DEPENDENCY ADD CONSTRAINT FK1_TBCOMPILE_DEPENDENCY  FOREIGN KEY (ID)
	REFERENCES TBCATALOG_ITEM (ID);           
----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS TBPROPERTY_CATALOG_ITEM;

CREATE TABLE TBPROPERTY_CATALOG_ITEM (
		FK_CATALOG_ID VARCHAR(255) NOT NULL,
		PROPERTY_KEY VARCHAR(255) NOT NULL,
		PROPERTY_VALUE VARCHAR(255) NOT NULL
	);
    
CREATE INDEX IX_PK_TBPROPERTY_CATALOG_ITEM ON TBPROPERTY_CATALOG_ITEM(FK_CATALOG_ID, PROPERTY_KEY, PROPERTY_VALUE);    
ALTER TABLE TBPROPERTY_CATALOG_ITEM
  ADD CONSTRAINT PK_TBPROPERTY_CATALOG_ITEM
    PRIMARY KEY (FK_CATALOG_ID, PROPERTY_KEY, PROPERTY_VALUE);     

CREATE INDEX IX_FK1_TBPROPERTY_ ON TBPROPERTY_CATALOG_ITEM (FK_CATALOG_ID ASC);
ALTER TABLE TBPROPERTY_CATALOG_ITEM ADD CONSTRAINT FK1_TBPROPERTY_ITEM FOREIGN KEY (FK_CATALOG_ID)
	REFERENCES TBCATALOG_ITEM (ID);